[package]
name = "simple-calc"
version = "0.3.0"
authors = [
    "Pravin Kumar <pravinshanmugam1995@gmail.com>",
    "Brendan Doherty <2bndy5@gmail.com>",
]
edition = "2024"

[dependencies]
libm = "0.2.16"
thiserror = "2.0.18"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.bevy]
version = "0.18.1"
default-features = false
features = ["ui"]
